# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = obj/debug/mini_gl3core
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/mini_gl3core
  DEFINES   += -DGK_OPENGL3 -DVERBOSE -DDEBUG
  INCLUDES  += -I. -IgKit -ISDL/include -Iglew/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -mtune=native -W -Wall -Wno-unused-parameter -pipe -mtune=native -Og
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L/home/zloy/Documents/FRANCE/syntheseDImage/gKit2/glew/lib/ -Wl,-rpath,/home/zloy/Documents/FRANCE/syntheseDImage/gKit2/glew/lib/ -L/home/zloy/Documents/FRANCE/syntheseDImage/gKit2/SDL/lib/ -Wl,-rpath,/home/zloy/Documents/FRANCE/syntheseDImage/gKit2/SDL/lib/
  LIBS      += -lGLEW -lSDL2 -lSDL2_image -lSDL2_ttf -lGL
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/release/mini_gl3core
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/mini_gl3core
  DEFINES   += -DGK_OPENGL3 -DVERBOSE
  INCLUDES  += -I. -IgKit -ISDL/include -Iglew/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O3 -mtune=native -W -Wall -Wno-unused-parameter -pipe
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -L/home/zloy/Documents/FRANCE/syntheseDImage/gKit2/glew/lib/ -Wl,-rpath,/home/zloy/Documents/FRANCE/syntheseDImage/gKit2/glew/lib/ -L/home/zloy/Documents/FRANCE/syntheseDImage/gKit2/SDL/lib/ -Wl,-rpath,/home/zloy/Documents/FRANCE/syntheseDImage/gKit2/SDL/lib/
  LIBS      += -lGLEW -lSDL2 -lSDL2_image -lSDL2_ttf -lGL
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/mini_gl3core.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking mini_gl3core
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning mini_gl3core
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/mini_gl3core.o: mini_gl3core.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
